default: &default
  version: "2.0"

development:
  <<: *default
  api_server_url: "http://localhost:4000/api/v1"

test:
  <<: *default
  api_server_url: "http://localhost:4000/api/v1"

production:
  <<: *default
  api_server_url: "http://localhost/pubblicalo_api/api/v1"
